export const cyan = '#EAF6FA'
export const lightGray = '#4A4A4A'
export const red = '#D0021B'
export const white = '#FFFFFF'
export const lightBlue = '#00ADEE'
export const lightGreen = '#A5CD39'
export const darkGray = '#030303'
